export const ARENA_WIDTH = 700;
export const ARENA_HEIGHT = 700;
export const WALL_THICKNESS = 40;

export const SPHERE_RADIUS = 56;
export const SPHERE_RESTITUTION = 1;
export const SPHERE_FRICTION = 0;
export const SPHERE_DENSITY = 0.005;
export const SPHERE_AIR_FRICTION = 0;

export const DEFAULT_HP = 100;
export const VELOCITY_DAMAGE_MULTIPLIER = 0.8;
export const BASE_COLLISION_DAMAGE = 2;
export const DAMAGE_VELOCITY_THRESHOLD = 2;
export const BOUNCE_BOOST = 3.5;
export const MIN_WALL_BOUNCE_SPEED = 3;

export const WEAPON_SPRITE_SCALE = 5.25;
export const WEAPON_SPRITE_SIZE = 16 * WEAPON_SPRITE_SCALE;
export const PROJECTILE_SPRITE_SCALE = 3;

export const FIGHTER_COLORS = [
  '#4FC3F7',
  '#EF5350',
  '#66BB6A',
  '#FFA726',
];

export const ARENA_BG_COLOR = '#F5F0E1';
export const WALL_COLOR = '#333333';
export const FRAME_COLOR = '#2C2C2C';

export const SUPER_DURATION_MS = 6000;
export const SUPER_HIT_THRESHOLD = 5;

export const WEAPON_CONSTANTS: Record<string, {
  baseDamage: number;
  bodyWidth: number;
  bodyHeight: number;
  bodyDensity: number;
  bodyStiffness: number;
  projectileIntervalMs: number;
  projectileSpeed: number;
  projectileDamage: number;
  projectileWidth: number;
  projectileHeight: number;
  superThreshold: number;
  superDurationMs: number;
}> = {
  sword: {
    baseDamage: 10,
    bodyWidth: 60,
    bodyHeight: 10,
    bodyDensity: 0.002,
    bodyStiffness: 0.9,
    projectileIntervalMs: 0,
    projectileSpeed: 0,
    projectileDamage: 0,
    projectileWidth: 0,
    projectileHeight: 0,
    superThreshold: 5,
    superDurationMs: 6000,
  },
  dagger: {
    baseDamage: 6,
    bodyWidth: 30,
    bodyHeight: 6,
    bodyDensity: 0.001,
    bodyStiffness: 0.9,
    projectileIntervalMs: 0,
    projectileSpeed: 0,
    projectileDamage: 0,
    projectileWidth: 0,
    projectileHeight: 0,
    superThreshold: 5,
    superDurationMs: 6000,
  },
  spear: {
    baseDamage: 8,
    bodyWidth: 100,
    bodyHeight: 4,
    bodyDensity: 0.001,
    bodyStiffness: 0.9,
    projectileIntervalMs: 0,
    projectileSpeed: 0,
    projectileDamage: 0,
    projectileWidth: 0,
    projectileHeight: 0,
    superThreshold: 5,
    superDurationMs: 6000,
  },
  bow: {
    baseDamage: 0,
    bodyWidth: 40,
    bodyHeight: 8,
    bodyDensity: 0.001,
    bodyStiffness: 0.9,
    projectileIntervalMs: 1500,
    projectileSpeed: 10,
    projectileDamage: 10,
    projectileWidth: 16,
    projectileHeight: 4,
    superThreshold: 5,
    superDurationMs: 6000,
  },
  scythe: {
    baseDamage: 8,
    bodyWidth: 50,
    bodyHeight: 8,
    bodyDensity: 0.002,
    bodyStiffness: 0.9,
    projectileIntervalMs: 0,
    projectileSpeed: 0,
    projectileDamage: 0,
    projectileWidth: 0,
    projectileHeight: 0,
    superThreshold: 5,
    superDurationMs: 6000,
  },
  shield: {
    baseDamage: 2,
    bodyWidth: 40,
    bodyHeight: 50,
    bodyDensity: 0.02,
    bodyStiffness: 0.95,
    projectileIntervalMs: 0,
    projectileSpeed: 0,
    projectileDamage: 0,
    projectileWidth: 0,
    projectileHeight: 0,
    superThreshold: 5,
    superDurationMs: 6000,
  },
  scepter: {
    baseDamage: 6,
    bodyWidth: 30,
    bodyHeight: 6,
    bodyDensity: 0.001,
    bodyStiffness: 0.9,
    projectileIntervalMs: 0,
    projectileSpeed: 0,
    projectileDamage: 0,
    projectileWidth: 0,
    projectileHeight: 0,
    superThreshold: 5,
    superDurationMs: 6000,
  },
  unarmed: {
    baseDamage: 5,
    bodyWidth: 0,
    bodyHeight: 0,
    bodyDensity: 0,
    bodyStiffness: 0,
    projectileIntervalMs: 0,
    projectileSpeed: 0,
    projectileDamage: 0,
    projectileWidth: 0,
    projectileHeight: 0,
    superThreshold: 5,
    superDurationMs: 6000,
  },
  boots: {
    baseDamage: 5,
    bodyWidth: 0,
    bodyHeight: 0,
    bodyDensity: 0,
    bodyStiffness: 0,
    projectileIntervalMs: 0,
    projectileSpeed: 0,
    projectileDamage: 0,
    projectileWidth: 0,
    projectileHeight: 0,
    superThreshold: Infinity,
    superDurationMs: 0,
  },
  staff: {
    baseDamage: 4,
    bodyWidth: 70,
    bodyHeight: 5,
    bodyDensity: 0.001,
    bodyStiffness: 0.9,
    projectileIntervalMs: 1200,
    projectileSpeed: 8,
    projectileDamage: 12,
    projectileWidth: 12,
    projectileHeight: 12,
    superThreshold: 5,
    superDurationMs: 6000,
  },
  shuriken: {
    baseDamage: 0,
    bodyWidth: 0,
    bodyHeight: 0,
    bodyDensity: 0,
    bodyStiffness: 0,
    projectileIntervalMs: 2000,
    projectileSpeed: 9,
    projectileDamage: 8,
    projectileWidth: 14,
    projectileHeight: 14,
    superThreshold: 5,
    superDurationMs: 6000,
  },
  wrench: {
    baseDamage: 7,
    bodyWidth: 25,
    bodyHeight: 15,
    bodyDensity: 0.002,
    bodyStiffness: 0.9,
    projectileIntervalMs: 0,
    projectileSpeed: 0,
    projectileDamage: 0,
    projectileWidth: 0,
    projectileHeight: 0,
    superThreshold: 5,
    superDurationMs: 6000,
  },
  hammer: {
    baseDamage: 12,
    bodyWidth: 50,
    bodyHeight: 20,
    bodyDensity: 0.008,
    bodyStiffness: 0.9,
    projectileIntervalMs: 0,
    projectileSpeed: 0,
    projectileDamage: 0,
    projectileWidth: 0,
    projectileHeight: 0,
    superThreshold: 5,
    superDurationMs: 6000,
  },
  katana: {
    baseDamage: 8,
    bodyWidth: 55,
    bodyHeight: 5,
    bodyDensity: 0.001,
    bodyStiffness: 0.9,
    projectileIntervalMs: 0,
    projectileSpeed: 0,
    projectileDamage: 0,
    projectileWidth: 0,
    projectileHeight: 0,
    superThreshold: 5,
    superDurationMs: 6000,
  },
  flask: {
    baseDamage: 0,
    bodyWidth: 0,
    bodyHeight: 0,
    bodyDensity: 0,
    bodyStiffness: 0,
    projectileIntervalMs: 2000,
    projectileSpeed: 7,
    projectileDamage: 5,
    projectileWidth: 10,
    projectileHeight: 10,
    superThreshold: 5,
    superDurationMs: 6000,
  },
  lance: {
    baseDamage: 10,
    bodyWidth: 120,
    bodyHeight: 3,
    bodyDensity: 0.001,
    bodyStiffness: 0.9,
    projectileIntervalMs: 0,
    projectileSpeed: 0,
    projectileDamage: 0,
    projectileWidth: 0,
    projectileHeight: 0,
    superThreshold: 5,
    superDurationMs: 6000,
  },
  grimoire: {
    baseDamage: 4,
    bodyWidth: 30,
    bodyHeight: 25,
    bodyDensity: 0.001,
    bodyStiffness: 0.9,
    projectileIntervalMs: 0,
    projectileSpeed: 0,
    projectileDamage: 0,
    projectileWidth: 0,
    projectileHeight: 0,
    superThreshold: 5,
    superDurationMs: 6000,
  },
  axe: {
    baseDamage: 10,
    bodyWidth: 45,
    bodyHeight: 18,
    bodyDensity: 0.004,
    bodyStiffness: 0.9,
    projectileIntervalMs: 0,
    projectileSpeed: 0,
    projectileDamage: 0,
    projectileWidth: 0,
    projectileHeight: 0,
    superThreshold: 5,
    superDurationMs: 6000,
  },
  boomerang: {
    baseDamage: 0,
    bodyWidth: 0,
    bodyHeight: 0,
    bodyDensity: 0,
    bodyStiffness: 0,
    projectileIntervalMs: 3000,
    projectileSpeed: 8,
    projectileDamage: 8,
    projectileWidth: 30,
    projectileHeight: 10,
    superThreshold: 5,
    superDurationMs: 6000,
  },
  flail: {
    baseDamage: 10,
    bodyWidth: 30,
    bodyHeight: 30,
    bodyDensity: 0.006,
    bodyStiffness: 0.5,
    projectileIntervalMs: 0,
    projectileSpeed: 0,
    projectileDamage: 0,
    projectileWidth: 0,
    projectileHeight: 0,
    superThreshold: Infinity,
    superDurationMs: 0,
  },
  crossbow: {
    baseDamage: 0,
    bodyWidth: 40,
    bodyHeight: 10,
    bodyDensity: 0.001,
    bodyStiffness: 0.9,
    projectileIntervalMs: 1000,
    projectileSpeed: 12,
    projectileDamage: 8,
    projectileWidth: 14,
    projectileHeight: 3,
    superThreshold: 5,
    superDurationMs: 6000,
  },
  torch: {
    baseDamage: 5,
    bodyWidth: 30,
    bodyHeight: 8,
    bodyDensity: 0.001,
    bodyStiffness: 0.9,
    projectileIntervalMs: 0,
    projectileSpeed: 0,
    projectileDamage: 0,
    projectileWidth: 0,
    projectileHeight: 0,
    superThreshold: 5,
    superDurationMs: 6000,
  },
  rapier: {
    baseDamage: 7,
    bodyWidth: 70,
    bodyHeight: 3,
    bodyDensity: 0.001,
    bodyStiffness: 0.9,
    projectileIntervalMs: 0,
    projectileSpeed: 0,
    projectileDamage: 0,
    projectileWidth: 0,
    projectileHeight: 0,
    superThreshold: Infinity,
    superDurationMs: 0,
  },
  scroll: {
    baseDamage: 3,
    bodyWidth: 25,
    bodyHeight: 20,
    bodyDensity: 0.001,
    bodyStiffness: 0.9,
    projectileIntervalMs: 0,
    projectileSpeed: 0,
    projectileDamage: 0,
    projectileWidth: 0,
    projectileHeight: 0,
    superThreshold: Infinity,
    superDurationMs: 0,
  },
};

export const SCALING = {
  sword: { damagePerHit: 1 },
  dagger: { rotationPerHit: 0.1, maxRotation: 10 },
  spear: { sizePerHit: 0.5, damagePerHit: 0.5, superRotationMultiplier: 1.5 },
  bow: { arrowCountPerHit: 1 },
  scythe: { poisonDPSPerStack: 2 },
  shield: { widthPercentPerHit: 5 },
  scepter: { lifestealPerHit: 0.5, allyHealFraction: 0.3 },
  unarmed: { speedPerHit: 1, speedDamageFactor: 0.5 },
  boots: { speedPerHit: 1, speedDamageFactor: 0.5, radiusMultiplier: 0.7 },
  staff: { fireballDamagePerHit: 0.5, fireballSizePerHit: 0.5 },
  shuriken: { bouncePerHit: 1, superBouncePerHit: 2 },
  wrench: { turretDamage: 5, turretFireMs: 800, turretLifetimeMs: 8000, superBarrels: 3, superDamageMultiplier: 1.3 },
  hammer: { rotationPerHit: 1, maxRotation: 20, damagePerRotation: 1 },
  katana: { slashPerHit: 1, tickIntervalMs: 200, tickDamage: 2 },
  flask: { spillDPSPerHit: 1, spillRadius: 50, spillDurationMs: 4000, superCooldownMultiplier: 0.25 },
  lance: { joustDamagePerHit: 2, joustIntervalMs: 3000, joustSpeed: 15, joustDurationMs: 500 },
  grimoire: { minionHpPerHit: 1, minionBaseHp: 20, minionSpeed: 3 },
  axe: { critChancePerHit: 2, superCritMin: 20, superCritMax: 100 },
  boomerang: { damagePerHit: 2, returnTimeMs: 1500, superCooldownMultiplier: 0.5 },
  flail: { sizePerHit: 0.5, damagePerHit: 0.5 },
  crossbow: { boltDamagePerHit: 1, superFireRateMultiplier: 2.44 },
  torch: { flameLifetimePerHit: 1000, flameBaseLifetimeMs: 3000, flameDPS: 3, flameRadius: 25 },
  rapier: { lungeRatePerHit: 0.2, lungeDamagePerHit: 1, lungeBaseCooldownMs: 2000, lungeSpeed: 20, lungeDurationMs: 200 },
  scroll: { letterRatePerHit: 0.2, letterBaseIntervalMs: 2000, letterOrbitRadius: 80, letterOrbitSpeed: 2, letterDamage: 3 },
};
